# Generated by Django 5.2.6 on 2025-09-06 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('account_holder', models.CharField(max_length=150, verbose_name='Titular da Conta')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='MachinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Máquina')),
                ('min_investment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mínimo de Investimento')),
                ('return_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retorno (%)')),
                ('lifespan_days', models.IntegerField(verbose_name='Tempo de Vida do Investimento (dias)')),
                ('expiration_date', models.DateField(verbose_name='Data de Expiração da Máquina (deixa de estar disponível)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativa para novos investimentos?')),
            ],
            options={
                'verbose_name': 'Máquina de Investimento',
                'verbose_name_plural': 'Máquinas de Investimento',
            },
        ),
        migrations.CreateModel(
            name='VIPLevel',
            fields=[
                ('level_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Número do Nível')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Nível')),
                ('min_total_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_successful_referrals', models.PositiveIntegerField(default=0)),
                ('withdrawal_fee_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Nível VIP',
                'verbose_name_plural': 'Níveis VIP',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Investido')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.machineplan', verbose_name='Máquina Investida')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retirada'), ('INVESTMENT', 'Investimento'), ('EARNING', 'Ganho'), ('BONUS', 'Bónus de Convite')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Em Processamento'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='proof_payments/')),
                ('destination_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_terms', models.BooleanField(default=False)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vip_level', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.viplevel')),
            ],
        ),
        migrations.AddField(
            model_name='machineplan',
            name='required_vip_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.viplevel'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invested_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
