# Generated by Django 5.2.6 on 2025-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_viplevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/', verbose_name='Imagem da Máquina'),
        ),
    ]
