# Generated by Django 5.2.6 on 2025-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machineplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Titular (Saque)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Conta (Saque)'),
        ),
    ]
