# Generated by Django 5.2.6 on 2025-09-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_withdrawal_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Código de Pagamento (Encriptado)'),
        ),
    ]
